# Travis-CI configuration file for SuperTuxKart
#
# Configuration manual:
# http://docs.travis-ci.com/user/build-configuration/

language: cpp
compiler: g++

sudo: false

addons:
  apt:
    sources:
	  - ubuntu-toolchain-r-test
	  - ubuntu-sdk-team
	packages:
      - build-essential
	  - libgl1-mesa-dev
      - g++-4.8

script:
  - export CXX="g++-4.8"
  - qmake --version
  - qmake "QMAKE_CXX=$CXX"
  - make
