# Travis-CI configuration file for SuperTuxKart
#
# Configuration manual:
# http://docs.travis-ci.com/user/build-configuration/

language: cpp
compiler: g++
	  
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-add-repository ppa:ubuntu-sdk-team/ppa -y
  - sudo apt-get update -qq

install:
  - sudo apt-get install g++-4.9 -qq
  - export CXX="g++-4.9"
  - sudo apt-get install build-essential libgl1-mesa-dev

script:
  - qmake --version
  - qmake "QMAKE_CXX=$CXX"
  - make
